stages:
- name: jadikan image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: agussang/gmedia:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    when:
      branch:
        include:
        - master
  when:
    branch:
      include:
      - master
- name: deployk8s
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: '#pesuruh'
    notifier: c-gllwf:n-hpwzm
  condition:
  - Success
  - Changed
<<<<<<< HEAD
<<<<<<< HEAD
  - Failed
=======
  - Failed
>>>>>>> de37ad3aadbdf274ecf9e9363d56b22bc0a91db8
=======
  - Failed
>>>>>>> ac30904408b6a7b3b705f5f1b743300fda31d5a4
